# Generated by Django 3.2.8 on 2021-11-12 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20211112_0336'),
    ]

    operations = [
        migrations.RenameField(
            model_name='departamento',
            old_name='edificio',
            new_name='edificios',
        ),
        migrations.RenameField(
            model_name='departamento',
            old_name='propietario',
            new_name='propietarios',
        ),
    ]
