# Generated by Django 3.2.8 on 2021-11-12 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20211112_0337'),
    ]

    operations = [
        migrations.RenameField(
            model_name='departamento',
            old_name='edificios',
            new_name='edificio',
        ),
        migrations.RenameField(
            model_name='departamento',
            old_name='propietarios',
            new_name='propietario',
        ),
    ]
